### ISSUE TITLE
[Advice] properly managing Python dependencies

### ISSUE THREAD

**Issue by jingfelix** [moxin-org/mofa#26]
## 遇到的问题

当前安装和使用 mofa 的方法是：

```shell
pip install -r requirements.txt
```

然而，该`requirements.txt`文件包含的依赖项较多，其中不乏`sentence-transformers`这样依赖项较多，或`ultralytics`这样仅在 exmaple 中需要使用的依赖项。如果仅需要使用基本的 Agent 功能，这些依赖项的存在为开发者搭建环境或打包镜像造成了一定影响。

<img width="171" alt="image" src="https://github.com/user-attachments/assets/cae50627-591f-4cdc-a18e-d7b2015075bd">

## 可能的建议

1. 换用`pdm`或`poetry`等支持依赖组（dependency group）功能的包管理器，将 example/vectordb/dev 等功能所需的依赖项进行分离
2. 或拆分`requirements.txt`为多个文件，安装时根据不同的需求选择安装

**Comment by chengzi0103** [comment]
> ## 遇到的问题
> 当前安装和使用 mofa 的方法是：
> 
> ```shell
> pip install -r requirements.txt
> ```
> 
> 然而，该`requirements.txt`文件包含的依赖项较多，其中不乏`sentence-transformers`这样依赖项较多，或`ultralytics`这样仅在 exmaple 中需要使用的依赖项。如果仅需要使用基本的 Agent 功能，这些依赖项的存在为开发者搭建环境或打包镜像造成了一定影响。
> 
> <img alt="image" width="171" src="https://private-user-images.githubusercontent.com/72600955/376040086-cae50627-591f-4cdc-a18e-d7b2015075bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Mjk2MTQsIm5iZiI6MTczMDQyOTMxNCwicGF0aCI6Ii83MjYwMDk1NS8zNzYwNDAwODYtY2FlNTA2MjctNTkxZi00Y2RjLWExOGUtZDdiMjAxNTA3NWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAyNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NzFlYTNmZjgzZDYxZWViZDY1YzBhNTU5YWNlYzhmYzQ3MDcyMjY3ZjNkN2YxZTc5YTQ2YTk0ZDlkZTlkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FQ6vwrXMD0Nx47tAAadMwJCFQlDbHr-wf7jdRTEaCD4">
> ## 可能的建议
> 1. 换用`pdm`或`poetry`等支持依赖组（dependency group）功能的包管理器，将 example/vectordb/dev 等功能所需的依赖项进行分离
> 2. 或拆分`requirements.txt`为多个文件，安装时根据不同的需求选择安装

当然 谢谢你的建议 
我们会在后期单独根据examples中的不同案例 重新创建不同的依赖

**Comment by chengzi0103** [comment]
close
